"""Configuration and constants for the Contextual AI RAG demo."""

import os

API_KEY = os.environ.get("CONTEXTUAL_API_KEY")
if not API_KEY:
    raise RuntimeError(
        "Set the CONTEXTUAL_API_KEY environment variable before running this script."
    )

DATA_DIR = "data"
DATASTORE_NAME = "Financial_Demo_RAG"
AGENT_NAME = "Demo"

# (filename, source url) pairs for the demo corpus.
FILES_TO_UPLOAD = [
    # NVIDIA quarterly revenue 24/25
    (
        "A_Rev_by_Mkt_Qtrly_Trend_Q425.pdf",
        "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/A_Rev_by_Mkt_Qtrly_Trend_Q425.pdf",
    ),
    # NVIDIA quarterly revenue 22/23
    (
        "B_Q423-Qtrly-Revenue-by-Market-slide.pdf",
        "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/B_Q423-Qtrly-Revenue-by-Market-slide.pdf",
    ),
    # Spurious correlations report - fun example of graphs and statistical analysis
    (
        "C_Neptune.pdf",
        "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/C_Neptune.pdf",
    ),
    # Another spurious correlations report - fun example of graphs and statistical analysis
    (
        "D_Unilever.pdf",
        "https://raw.githubusercontent.com/ContextualAI/examples/refs/heads/main/08-ai-workshop/data/D_Unilever.pdf",
    ),
]

SYSTEM_PROMPT = """
You are a helpful AI assistant created by Contextual AI to answer questions about relevant documentation provided to you. Your responses should be precise, accurate, and sourced exclusively from the provided information. Please follow these guidelines:
* Only use information from the provided documentation. Avoid opinions, speculation, or assumptions.
* Use the exact terminology and descriptions found in the provided content.
* Keep answers concise and relevant to the user's question.
* Use acronyms and abbreviations exactly as they appear in the documentation or query.
* Apply markdown if your response includes lists, tables, or code.
* Directly answer the question, then STOP. Avoid additional explanations unless specifically relevant.
* If the information is irrelevant, simply respond that you don't have relevant documentation and do not provide additional comments or suggestions. Ignore anything that cannot be used to directly answer this query.
"""

SUGGESTED_QUERIES = [
    "What was NVIDIA's annual revenue by fiscal year 2022 to 2025?",
    "When did NVIDIA's data center revenue overtake gaming revenue?",
    "What's the correlation between the distance between Neptune and the Sun and Burglary rates in the US?",
    "What's the correlation between Global revenue generated by Unilever Group and Google searches for 'lost my wallet'?",
    "Does this imply that Unilever Group's revenue is derived from lost wallets?",
    "What's the correlation between the distance between Neptune and the Sun and Global revenue generated by Unilever Group?",
]

DEMO_QUERY = "What was NVIDIA's annual revenue by fiscal year 2022 to 2025?"

UNIT_TESTS = [
    "Does the response accurately extract specific numerical data from the documents?",
    "Does the agent properly distinguish between correlation and causation?",
    "Are multi-document comparisons performed correctly with accurate calculations?",
    "Are potential limitations or uncertainties in the data clearly acknowledged?",
    "Are quantitative claims properly supported with specific evidence from the source documents?",
    "Does the response avoid unnecessary information?",
]

EVAL_QUERIES = [
    "What was NVIDIA's Data Center revenue in Q4 FY25?",
    "What is the correlation coefficient between Neptune's distance from the Sun and US burglary rates?",
    "How did NVIDIA's total revenue change from Q1 FY22 to Q4 FY25?",
    "What are the four main reasons why spurious correlations work, according to the Tyler Vigen documents?",
    "Why should we be skeptical of the correlation between Unilever's revenue and Google searches for 'lost my wallet'?",
    "When did NVIDIA's data center revenue overtake gaming revenue?",
]

# Maps a unit-test question to the short category label used in the radar plots.
TEST_CATEGORY_MAPPING = {
    "does the response accurately extract specific numerical data": "ACCURACY",
    "does the agent properly distinguish between correlation and causation": "CAUSATION",
    "are multi-document comparisons performed correctly": "SYNTHESIS",
    "are potential limitations or uncertainties in the data": "LIMITATIONS",
    "are quantitative claims properly supported with specific evidence": "EVIDENCE",
    "does the response avoid unnecessary information": "RELEVANCE",
}
