"""The Agent2Agent (A2A) Protocol
The Agent2Agent (A2A) Protocol is an open standard communication protocol designed to help AI agents talk to each other.

Agent Card : Describes an agent's capabilities, authentication requirements, and how to interact with it.
Task Object : The central data object representing a piece of work to be done. It has an ID, status, messages, artifacts, etc.
Message Object : Represents a conversational turn or a piece of information being exchanged, typically part of a Task. It contains Part objects.
Part Union Type : Defines the content of a message, such as TextPart, FilePart, or DataPart. We'll primarily use TextPart.
Artifact Object : Represents outputs or results generated by a task, like files or structured data.
JSON-RPC : A2A uses JSON-RPC for its remote procedure calls. Key methods include tasks/send, tasks/get, tasks/cancel.


    A2A vs MCP (Model Context Protocol)
MCP (Model Context Protocol): Focuses on standardizing how AI models and agents connect to and interact with tools, APIs, data sources, and other external resources. It's about how an agent uses a capability.
A2A (Agent2Agent Protocol): Focuses on standardizing how independent AI agents communicate and collaborate with each other as peers. It's about how agents partner or delegate work.
"""
